services:
  mailscript:
    container_name: mailscript
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
    command: python get_mails.py
